/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package healthfirstpims;

/**
 *
 * @author user
 */
public class ManageMedicines extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(ManageMedicines.class.getName());

    /**
     * Creates new form ManageMedicines
     */
    public ManageMedicines() {
        initComponents();
        loadMedicines();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton2 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txtMedicineName = new javax.swing.JTextField();
        txtCompany = new javax.swing.JTextField();
        txtMedicineType = new javax.swing.JTextField();
        txtPrice = new javax.swing.JTextField();
        txtQuantity = new javax.swing.JTextField();
        txtReorderLevel = new javax.swing.JTextField();
        txtExpiryDate = new javax.swing.JTextField();
        txtSupplierId = new javax.swing.JTextField();
        btnAdd = new javax.swing.JButton();
        btnUpdate = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();
        btnClear = new javax.swing.JButton();
        btnBack = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblMedicines = new javax.swing.JTable();
        jLabel9 = new javax.swing.JLabel();

        jButton2.setText("jButton2");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("HealthFirst Pharmacy - Manage Medicines");
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                formMouseClicked(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 22)); // NOI18N
        jLabel1.setText("MEDICINE MANAGEMENT");

        jLabel2.setText("Medicine Name:");

        jLabel3.setText("Company:");

        jLabel4.setText("Medicine Type:");

        jLabel5.setText("Price:");

        jLabel6.setText("Quantity:");

        jLabel7.setText("Reorder Level:");

        jLabel8.setText("Expiry Date;");

        txtMedicineName.addActionListener(this::txtMedicineNameActionPerformed);

        txtPrice.addActionListener(this::txtPriceActionPerformed);

        txtQuantity.addActionListener(this::txtQuantityActionPerformed);

        btnAdd.setText("ADD");
        btnAdd.addActionListener(this::btnAddActionPerformed);

        btnUpdate.setText("UPDATE");
        btnUpdate.addActionListener(this::btnUpdateActionPerformed);

        btnDelete.setText("DELETE");
        btnDelete.addActionListener(this::btnDeleteActionPerformed);

        btnClear.setText("CLEAR");
        btnClear.addActionListener(this::btnClearActionPerformed);

        btnBack.setText("BACK");
        btnBack.addActionListener(this::btnBackActionPerformed);

        tblMedicines.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblMedicines.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblMedicinesMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblMedicines);

        jLabel9.setText("SupplierId:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel4)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(21, 21, 21)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtMedicineName)
                            .addComponent(txtCompany)
                            .addComponent(txtMedicineType)
                            .addComponent(txtPrice)
                            .addComponent(txtQuantity)
                            .addComponent(txtReorderLevel)
                            .addComponent(txtExpiryDate)))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btnAdd)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnUpdate)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnDelete)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnClear))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(txtSupplierId)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 56, Short.MAX_VALUE)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(50, 50, 50))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(165, 165, 165)
                        .addComponent(btnBack)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(242, 242, 242))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(130, 130, 130)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(txtMedicineName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(txtCompany, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel4)
                            .addComponent(txtMedicineType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtPrice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtQuantity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtReorderLevel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtExpiryDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtSupplierId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 29, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                        .addGap(18, 18, 18)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnUpdate)
                        .addComponent(btnDelete)
                        .addComponent(btnAdd)
                        .addComponent(btnClear))
                    .addComponent(btnBack))
                .addGap(110, 110, 110))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtPriceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPriceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPriceActionPerformed

    private void txtQuantityActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtQuantityActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtQuantityActionPerformed

    private void txtMedicineNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMedicineNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMedicineNameActionPerformed

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed

String name = txtMedicineName.getText().trim();
String company = txtCompany.getText().trim();
String type = txtMedicineType.getText().trim();
String priceText = txtPrice.getText().trim();
String quantityText = txtQuantity.getText().trim();
String reorderText = txtReorderLevel.getText().trim();
String expiryText = txtExpiryDate.getText().trim();
String supplierText = txtSupplierId.getText().trim();

if (name.isEmpty() || company.isEmpty() || type.isEmpty()
        || priceText.isEmpty() || quantityText.isEmpty()
        || reorderText.isEmpty() || expiryText.isEmpty()
        || supplierText.isEmpty()) {

    javax.swing.JOptionPane.showMessageDialog(
            this,
            "Please complete all medicine fields."
    );
    return;
}

try {

    double price = Double.parseDouble(priceText);
    int quantity = Integer.parseInt(quantityText);
    int reorderLevel = Integer.parseInt(reorderText);
    int supplierId = Integer.parseInt(supplierText);

    java.sql.Date expiryDate =
            java.sql.Date.valueOf(expiryText);

    String sql = "INSERT INTO medicines "
            + "(name, company, medicine_type, price, quantity_in_stock, "
            + "reorder_level, expiry_date, supplier_id) "
            + "VALUES (?, ?, ?, ?, ?, ?, ?, ?)";

    try (
        java.sql.Connection con = DBConnection.getConnection();
        java.sql.PreparedStatement pst = con.prepareStatement(sql)
    ) {

        pst.setString(1, name);
        pst.setString(2, company);
        pst.setString(3, type);
        pst.setDouble(4, price);
        pst.setInt(5, quantity);
        pst.setInt(6, reorderLevel);
        pst.setDate(7, expiryDate);
        pst.setInt(8, supplierId);

        pst.executeUpdate();

        javax.swing.JOptionPane.showMessageDialog(
                this,
                "Medicine added successfully!"
        );

        loadMedicines();
    }

} catch (NumberFormatException e) {

    javax.swing.JOptionPane.showMessageDialog(
            this,
            "Price, Quantity, Reorder Level and Supplier ID must contain valid numbers."
    );

} catch (IllegalArgumentException e) {

    javax.swing.JOptionPane.showMessageDialog(
            this,
            "Expiry Date must use YYYY-MM-DD format."
    );

} catch (java.sql.SQLException e) {

    javax.swing.JOptionPane.showMessageDialog(
            this,
            "Could not add medicine:\n" + e.getMessage(),
            "Database Error",
            javax.swing.JOptionPane.ERROR_MESSAGE
    );
}       // TODO add your handling code here:
    }//GEN-LAST:event_btnAddActionPerformed

    private void btnClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClearActionPerformed
        txtMedicineName.setText("");
        txtCompany.setText("");
        txtMedicineType.setText("");
        txtPrice.setText("");
        txtQuantity.setText("");
        txtReorderLevel.setText("");
        txtExpiryDate.setText("");
        txtSupplierId.setText("");

        tblMedicines.clearSelection();
        txtMedicineName.requestFocus();// TODO add your handling code here:
    }//GEN-LAST:event_btnClearActionPerformed

    private void formMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_formMouseClicked

    private void tblMedicinesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblMedicinesMouseClicked
       int selectedRow = tblMedicines.getSelectedRow();

if (selectedRow != -1) {
    txtMedicineName.setText(tblMedicines.getValueAt(selectedRow, 1).toString());
    txtCompany.setText(tblMedicines.getValueAt(selectedRow, 2).toString());
    txtMedicineType.setText(tblMedicines.getValueAt(selectedRow, 3).toString());
    txtPrice.setText(tblMedicines.getValueAt(selectedRow, 4).toString());
    txtQuantity.setText(tblMedicines.getValueAt(selectedRow, 5).toString());
    txtReorderLevel.setText(tblMedicines.getValueAt(selectedRow, 6).toString());
    txtExpiryDate.setText(tblMedicines.getValueAt(selectedRow, 7).toString());
    txtSupplierId.setText(tblMedicines.getValueAt(selectedRow, 8).toString());
} // TODO add your handling code here:
    }//GEN-LAST:event_tblMedicinesMouseClicked

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
       int selectedRow = tblMedicines.getSelectedRow();

if (selectedRow == -1) {
    javax.swing.JOptionPane.showMessageDialog(
            this,
            "Please select a medicine from the table first."
    );
    return;
}

int medicineId = Integer.parseInt(
        tblMedicines.getValueAt(selectedRow, 0).toString()
);

String name = txtMedicineName.getText().trim();
String company = txtCompany.getText().trim();
String type = txtMedicineType.getText().trim();
String priceText = txtPrice.getText().trim();
String quantityText = txtQuantity.getText().trim();
String reorderText = txtReorderLevel.getText().trim();
String expiryText = txtExpiryDate.getText().trim();
String supplierText = txtSupplierId.getText().trim();

if (name.isEmpty() || company.isEmpty() || type.isEmpty()
        || priceText.isEmpty() || quantityText.isEmpty()
        || reorderText.isEmpty() || expiryText.isEmpty()
        || supplierText.isEmpty()) {

    javax.swing.JOptionPane.showMessageDialog(
            this,
            "Please complete all medicine fields."
    );
    return;
}

try {

    double price = Double.parseDouble(priceText);
    int quantity = Integer.parseInt(quantityText);
    int reorderLevel = Integer.parseInt(reorderText);
    int supplierId = Integer.parseInt(supplierText);
    java.sql.Date expiryDate = java.sql.Date.valueOf(expiryText);

    String sql = "UPDATE medicines SET "
            + "name = ?, company = ?, medicine_type = ?, price = ?, "
            + "quantity_in_stock = ?, reorder_level = ?, "
            + "expiry_date = ?, supplier_id = ? "
            + "WHERE medicine_id = ?";

    try (
        java.sql.Connection con = DBConnection.getConnection();
        java.sql.PreparedStatement pst = con.prepareStatement(sql)
    ) {

        pst.setString(1, name);
        pst.setString(2, company);
        pst.setString(3, type);
        pst.setDouble(4, price);
        pst.setInt(5, quantity);
        pst.setInt(6, reorderLevel);
        pst.setDate(7, expiryDate);
        pst.setInt(8, supplierId);
        pst.setInt(9, medicineId);

        pst.executeUpdate();

        javax.swing.JOptionPane.showMessageDialog(
                this,
                "Medicine updated successfully!"
        );

        loadMedicines();
    }

} catch (NumberFormatException e) {

    javax.swing.JOptionPane.showMessageDialog(
            this,
            "Price, Quantity, Reorder Level and Supplier ID must contain valid numbers."
    );

} catch (IllegalArgumentException e) {

    javax.swing.JOptionPane.showMessageDialog(
            this,
            "Expiry Date must use YYYY-MM-DD format."
    );

} catch (java.sql.SQLException e) {

    javax.swing.JOptionPane.showMessageDialog(
            this,
            "Could not update medicine:\n" + e.getMessage(),
            "Database Error",
            javax.swing.JOptionPane.ERROR_MESSAGE
    );
} // TODO add your handling code here:
    }//GEN-LAST:event_btnUpdateActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        int selectedRow = tblMedicines.getSelectedRow();

if (selectedRow == -1) {
    javax.swing.JOptionPane.showMessageDialog(
            this,
            "Please select a medicine from the table first."
    );
    return;
}

int medicineId = Integer.parseInt(
        tblMedicines.getValueAt(selectedRow, 0).toString()
);

String medicineName =
        tblMedicines.getValueAt(selectedRow, 1).toString();

int confirm = javax.swing.JOptionPane.showConfirmDialog(
        this,
        "Are you sure you want to delete " + medicineName + "?",
        "Confirm Delete",
        javax.swing.JOptionPane.YES_NO_OPTION
);

if (confirm != javax.swing.JOptionPane.YES_OPTION) {
    return;
}

String sql = "DELETE FROM medicines WHERE medicine_id = ?";

try (
    java.sql.Connection con = DBConnection.getConnection();
    java.sql.PreparedStatement pst = con.prepareStatement(sql)
) {

    pst.setInt(1, medicineId);

    pst.executeUpdate();

    javax.swing.JOptionPane.showMessageDialog(
            this,
            "Medicine deleted successfully!"
    );

    loadMedicines();

    txtMedicineName.setText("");
    txtCompany.setText("");
    txtMedicineType.setText("");
    txtPrice.setText("");
    txtQuantity.setText("");
    txtReorderLevel.setText("");
    txtExpiryDate.setText("");
    txtSupplierId.setText("");

} catch (java.sql.SQLException e) {

    javax.swing.JOptionPane.showMessageDialog(
            this,
            "Could not delete medicine:\n" + e.getMessage(),
            "Database Error",
            javax.swing.JOptionPane.ERROR_MESSAGE
    );
}// TODO add your handling code here:
    }//GEN-LAST:event_btnDeleteActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
       AdminDashboard dashboard = new AdminDashboard();
    dashboard.setVisible(true);
    dashboard.setLocationRelativeTo(null);

    this.dispose();
    }//GEN-LAST:event_btnBackActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new ManageMedicines().setVisible(true));
    }
private void loadMedicines() {

    String sql = "SELECT medicine_id, name, company, medicine_type, "
            + "price, quantity_in_stock, reorder_level, expiry_date, supplier_id "
            + "FROM medicines";

    try (
        java.sql.Connection con = DBConnection.getConnection();
        java.sql.PreparedStatement pst = con.prepareStatement(sql);
        java.sql.ResultSet rs = pst.executeQuery()
    ) {

        javax.swing.table.DefaultTableModel model =
                new javax.swing.table.DefaultTableModel(
                    new Object[]{
                        "ID",
                        "Medicine Name",
                        "Company",
                        "Type",
                        "Price",
                        "Quantity",
                        "Reorder Level",
                        "Expiry Date",
                        "Supplier ID"
                    }, 0
                );

        while (rs.next()) {

            Object[] row = {
                rs.getInt("medicine_id"),
                rs.getString("name"),
                rs.getString("company"),
                rs.getString("medicine_type"),
                rs.getBigDecimal("price"),
                rs.getInt("quantity_in_stock"),
                rs.getInt("reorder_level"),
                rs.getDate("expiry_date"),
                rs.getInt("supplier_id")
            };

            model.addRow(row);
        }

        tblMedicines.setModel(model);

    } catch (java.sql.SQLException e) {

        javax.swing.JOptionPane.showMessageDialog(
                this,
                "Could not load medicines:\n" + e.getMessage(),
                "Database Error",
                javax.swing.JOptionPane.ERROR_MESSAGE
        );
    }
}    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnClear;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblMedicines;
    private javax.swing.JTextField txtCompany;
    private javax.swing.JTextField txtExpiryDate;
    private javax.swing.JTextField txtMedicineName;
    private javax.swing.JTextField txtMedicineType;
    private javax.swing.JTextField txtPrice;
    private javax.swing.JTextField txtQuantity;
    private javax.swing.JTextField txtReorderLevel;
    private javax.swing.JTextField txtSupplierId;
    // End of variables declaration//GEN-END:variables





}
