/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package healthfirstpims;

/**
 *
 * @author user
 */
public class ManageSuppliers extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(ManageSuppliers.class.getName());

    /**
     * Creates new form ManageSuppliers
     */
    public ManageSuppliers() {
    initComponents();
    loadSuppliers();
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        label1 = new java.awt.Label();
        label2 = new java.awt.Label();
        label3 = new java.awt.Label();
        label4 = new java.awt.Label();
        label5 = new java.awt.Label();
        label6 = new java.awt.Label();
        label7 = new java.awt.Label();
        label8 = new java.awt.Label();
        txtSupplierName = new java.awt.TextField();
        txtContactPerson = new java.awt.TextField();
        txtPhone = new java.awt.TextField();
        txtEmail = new java.awt.TextField();
        txtAddress = new java.awt.TextField();
        btnAdd = new javax.swing.JButton();
        btnUpdate = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();
        btnClear = new javax.swing.JButton();
        btnBack = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblSuppliers = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        label2.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        label2.setText("SUPPLIER MANAGEMENT");

        label3.setText("Supplier Name:");
        label3.setVisible(false);

        label4.setText("Supplier Name:");

        label5.setText("Contact Person:");

        label6.setText("Phone:");

        label7.setText("Email:");

        label8.setText("Address:");

        txtSupplierName.addActionListener(this::txtSupplierNameActionPerformed);

        txtAddress.setName(""); // NOI18N

        btnAdd.setText("ADD");
        btnAdd.setActionCommand("ADD");
        btnAdd.addActionListener(this::btnAddActionPerformed);

        btnUpdate.setText("UPDATE");
        btnUpdate.addActionListener(this::btnUpdateActionPerformed);

        btnDelete.setText("DELETE");
        btnDelete.addActionListener(this::btnDeleteActionPerformed);

        btnClear.setText("CLEAR");
        btnClear.addActionListener(this::btnClearActionPerformed);

        btnBack.setText("BACK");
        btnBack.addActionListener(this::btnBackActionPerformed);

        tblSuppliers.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblSuppliers.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblSuppliersMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblSuppliers);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(752, 752, 752)
                        .addComponent(btnBack, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addComponent(btnAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnClear, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(192, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(98, 98, 98)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(label5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(label1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(label4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(label6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(label7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(label8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(label3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtSupplierName, javax.swing.GroupLayout.DEFAULT_SIZE, 163, Short.MAX_VALUE)
                            .addComponent(txtContactPerson, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtPhone, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtEmail, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtAddress, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 444, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(174, 174, 174))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(81, 81, 81)
                        .addComponent(label2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(20, Short.MAX_VALUE)
                .addComponent(label2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(260, 260, 260)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(label4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(8, 8, 8)
                                        .addComponent(label5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(label1, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(label3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(txtContactPerson, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(txtSupplierName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(28, 28, 28)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(label6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(txtPhone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(label7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(label8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtAddress, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 392, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addComponent(btnBack, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnClear)
                    .addComponent(btnDelete)
                    .addComponent(btnUpdate)
                    .addComponent(btnAdd))
                .addGap(58, 58, 58))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtSupplierNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSupplierNameActionPerformed
        String name = txtSupplierName.getText().trim();
String contactPerson = txtContactPerson.getText().trim();
String phone = txtPhone.getText().trim();
String email = txtEmail.getText().trim();
String address = txtAddress.getText().trim();

if (name.isEmpty() || contactPerson.isEmpty()
        || phone.isEmpty() || email.isEmpty()
        || address.isEmpty()) {

    javax.swing.JOptionPane.showMessageDialog(
            this,
            "Please complete all supplier fields."
    );
    return;
}

String sql = "INSERT INTO suppliers "
        + "(name, contact_person, phone, email, address) "
        + "VALUES (?, ?, ?, ?, ?)";

try (
    java.sql.Connection con = DBConnection.getConnection();
    java.sql.PreparedStatement pst = con.prepareStatement(sql)
) {

    pst.setString(1, name);
    pst.setString(2, contactPerson);
    pst.setString(3, phone);
    pst.setString(4, email);
    pst.setString(5, address);

    pst.executeUpdate();

    javax.swing.JOptionPane.showMessageDialog(
            this,
            "Supplier added successfully!"
    );

    loadSuppliers();

} catch (java.sql.SQLException e) {

    javax.swing.JOptionPane.showMessageDialog(
            this,
            "Could not add supplier:\n" + e.getMessage()
    );
}// TODO add your handling code here:
    }//GEN-LAST:event_txtSupplierNameActionPerformed

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
String name = txtSupplierName.getText().trim();
String contactPerson = txtContactPerson.getText().trim();
String phone = txtPhone.getText().trim();
String email = txtEmail.getText().trim();
String address = txtAddress.getText().trim();

if (name.isEmpty() || contactPerson.isEmpty()
        || phone.isEmpty() || email.isEmpty()
        || address.isEmpty()) {

    javax.swing.JOptionPane.showMessageDialog(
            this,
            "Please complete all supplier fields."
    );
    return;
}

String sql = "INSERT INTO suppliers "
        + "(name, contact_person, phone, email, address) "
        + "VALUES (?, ?, ?, ?, ?)";

try (
    java.sql.Connection con = DBConnection.getConnection();
    java.sql.PreparedStatement pst = con.prepareStatement(sql)
) {

    pst.setString(1, name);
    pst.setString(2, contactPerson);
    pst.setString(3, phone);
    pst.setString(4, email);
    pst.setString(5, address);

    pst.executeUpdate();

    javax.swing.JOptionPane.showMessageDialog(
            this,
            "Supplier added successfully!"
    );

    loadSuppliers();

} catch (java.sql.SQLException e) {

    javax.swing.JOptionPane.showMessageDialog(
            this,
            "Could not add supplier:\n" + e.getMessage()
    );
}// TODO add your handling code here:
    }//GEN-LAST:event_btnAddActionPerformed

    private void tblSuppliersMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblSuppliersMouseClicked
        int selectedRow = tblSuppliers.getSelectedRow();

if (selectedRow != -1) {
    txtSupplierName.setText(
            tblSuppliers.getValueAt(selectedRow, 1).toString());

    txtContactPerson.setText(
            tblSuppliers.getValueAt(selectedRow, 2).toString());

    txtPhone.setText(
            tblSuppliers.getValueAt(selectedRow, 3).toString());

    txtEmail.setText(
            tblSuppliers.getValueAt(selectedRow, 4).toString());

    txtAddress.setText(
            tblSuppliers.getValueAt(selectedRow, 5).toString());
}
    }//GEN-LAST:event_tblSuppliersMouseClicked

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
        // TODO add your handling code here:
        int selectedRow = tblSuppliers.getSelectedRow();

if (selectedRow == -1) {
    javax.swing.JOptionPane.showMessageDialog(
            this,
            "Please select a supplier from the table first."
    );
    return;
}

int supplierId = Integer.parseInt(
        tblSuppliers.getValueAt(selectedRow, 0).toString()
);

String name = txtSupplierName.getText().trim();
String contactPerson = txtContactPerson.getText().trim();
String phone = txtPhone.getText().trim();
String email = txtEmail.getText().trim();
String address = txtAddress.getText().trim();

if (name.isEmpty() || contactPerson.isEmpty()
        || phone.isEmpty() || email.isEmpty()
        || address.isEmpty()) {

    javax.swing.JOptionPane.showMessageDialog(
            this,
            "Please complete all supplier fields."
    );
    return;
}

String sql = "UPDATE suppliers SET "
        + "name = ?, contact_person = ?, phone = ?, "
        + "email = ?, address = ? "
        + "WHERE supplier_id = ?";

try (
    java.sql.Connection con = DBConnection.getConnection();
    java.sql.PreparedStatement pst = con.prepareStatement(sql)
) {

    pst.setString(1, name);
    pst.setString(2, contactPerson);
    pst.setString(3, phone);
    pst.setString(4, email);
    pst.setString(5, address);
    pst.setInt(6, supplierId);

    pst.executeUpdate();

    javax.swing.JOptionPane.showMessageDialog(
            this,
            "Supplier updated successfully!"
    );

    loadSuppliers();

} catch (java.sql.SQLException e) {

    javax.swing.JOptionPane.showMessageDialog(
            this,
            "Could not update supplier:\n" + e.getMessage()
    );
}
    }//GEN-LAST:event_btnUpdateActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        int selectedRow = tblSuppliers.getSelectedRow();

if (selectedRow == -1) {
    javax.swing.JOptionPane.showMessageDialog(
            this,
            "Please select a supplier from the table first."
    );
    return;
}

int supplierId = Integer.parseInt(
        tblSuppliers.getValueAt(selectedRow, 0).toString()
);

String supplierName =
        tblSuppliers.getValueAt(selectedRow, 1).toString();

int confirm = javax.swing.JOptionPane.showConfirmDialog(
        this,
        "Are you sure you want to delete " + supplierName + "?",
        "Confirm Delete",
        javax.swing.JOptionPane.YES_NO_OPTION
);

if (confirm != javax.swing.JOptionPane.YES_OPTION) {
    return;
}

String sql = "DELETE FROM suppliers WHERE supplier_id = ?";

try (
    java.sql.Connection con = DBConnection.getConnection();
    java.sql.PreparedStatement pst = con.prepareStatement(sql)
) {

    pst.setInt(1, supplierId);
    pst.executeUpdate();

    javax.swing.JOptionPane.showMessageDialog(
            this,
            "Supplier deleted successfully!"
    );

    loadSuppliers();

    txtSupplierName.setText("");
    txtContactPerson.setText("");
    txtPhone.setText("");
    txtEmail.setText("");
    txtAddress.setText("");

    tblSuppliers.clearSelection();

} catch (java.sql.SQLException e) {

    javax.swing.JOptionPane.showMessageDialog(
            this,
            "Could not delete supplier:\n" + e.getMessage(),
            "Database Error",
            javax.swing.JOptionPane.ERROR_MESSAGE
    );
}
    }//GEN-LAST:event_btnDeleteActionPerformed

    private void btnClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClearActionPerformed
        txtSupplierName.setText("");
txtContactPerson.setText("");
txtPhone.setText("");
txtEmail.setText("");
txtAddress.setText("");

tblSuppliers.clearSelection();
txtSupplierName.requestFocus();
    }//GEN-LAST:event_btnClearActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        AdminDashboard dashboard = new AdminDashboard();
dashboard.setVisible(true);
dashboard.setLocationRelativeTo(null);

this.dispose();
    }//GEN-LAST:event_btnBackActionPerformed
private void loadSuppliers() {

    javax.swing.table.DefaultTableModel model =
            new javax.swing.table.DefaultTableModel();

    model.addColumn("ID");
    model.addColumn("Supplier Name");
    model.addColumn("Contact Person");
    model.addColumn("Phone");
    model.addColumn("Email");
    model.addColumn("Address");

    String sql = "SELECT * FROM suppliers";

    try (
        java.sql.Connection con = DBConnection.getConnection();
        java.sql.PreparedStatement pst = con.prepareStatement(sql);
        java.sql.ResultSet rs = pst.executeQuery()
    ) {

        while (rs.next()) {

            model.addRow(new Object[]{
                rs.getInt("supplier_id"),
                rs.getString("name"),
                rs.getString("contact_person"),
                rs.getString("phone"),
                rs.getString("email"),
                rs.getString("address")
            });
        }

        tblSuppliers.setModel(model);

    } catch (java.sql.SQLException e) {

        javax.swing.JOptionPane.showMessageDialog(
                this,
                "Could not load suppliers:\n" + e.getMessage()
        );
    }
}

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new ManageSuppliers().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnClear;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JScrollPane jScrollPane1;
    private java.awt.Label label1;
    private java.awt.Label label2;
    private java.awt.Label label3;
    private java.awt.Label label4;
    private java.awt.Label label5;
    private java.awt.Label label6;
    private java.awt.Label label7;
    private java.awt.Label label8;
    private javax.swing.JTable tblSuppliers;
    private java.awt.TextField txtAddress;
    private java.awt.TextField txtContactPerson;
    private java.awt.TextField txtEmail;
    private java.awt.TextField txtPhone;
    private java.awt.TextField txtSupplierName;
    // End of variables declaration//GEN-END:variables
}
