/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package healthfirstpims;

/**
 *
 * @author user
 */
public class Reports extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Reports.class.getName());

    /**
     * Creates new form Reports
     */
    public Reports() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        btnSalesReport = new javax.swing.JButton();
        btnItemWiseReport = new javax.swing.JButton();
        btnLowStockReport = new javax.swing.JButton();
        btnExpiryReport = new javax.swing.JButton();
        btnBack = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setText("REPORTS");

        btnSalesReport.setBackground(new java.awt.Color(0, 133, 139));
        btnSalesReport.setText("SALES REPORT");
        btnSalesReport.addActionListener(this::btnSalesReportActionPerformed);

        btnItemWiseReport.setBackground(new java.awt.Color(0, 125, 132));
        btnItemWiseReport.setForeground(new java.awt.Color(255, 255, 255));
        btnItemWiseReport.setText("ITEM-WISE REPORT");
        btnItemWiseReport.addActionListener(this::btnItemWiseReportActionPerformed);

        btnLowStockReport.setBackground(new java.awt.Color(0, 123, 122));
        btnLowStockReport.setText("LOW STOCK REPORT");
        btnLowStockReport.addActionListener(this::btnLowStockReportActionPerformed);

        btnExpiryReport.setBackground(new java.awt.Color(0, 128, 143));
        btnExpiryReport.setForeground(new java.awt.Color(255, 255, 255));
        btnExpiryReport.setText("EXPIRY REPORT");
        btnExpiryReport.addActionListener(this::btnExpiryReportActionPerformed);

        btnBack.setFont(new java.awt.Font("Segoe UI Black", 1, 12)); // NOI18N
        btnBack.setText("BACK");
        btnBack.addActionListener(this::btnBackActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(170, 170, 170)
                .addComponent(jLabel1)
                .addContainerGap(150, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnSalesReport, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnItemWiseReport, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnLowStockReport, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnExpiryReport, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnBack, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addGap(76, 76, 76)
                .addComponent(btnSalesReport, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnItemWiseReport, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnLowStockReport, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnExpiryReport, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnBack)
                .addGap(0, 41, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        AdminDashboard dashboard = new AdminDashboard();
      dashboard.setVisible(true);
     dashboard.setLocationRelativeTo(null);
     this.dispose();
    }//GEN-LAST:event_btnBackActionPerformed

    private void btnSalesReportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalesReportActionPerformed
        SalesReport salesReport = new SalesReport();
         salesReport.setVisible(true);
         salesReport.setLocationRelativeTo(null);
         this.dispose();
    }//GEN-LAST:event_btnSalesReportActionPerformed

    private void btnItemWiseReportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnItemWiseReportActionPerformed
        ItemWiseReport itemReport = new ItemWiseReport();
         itemReport.setVisible(true);
        itemReport.setLocationRelativeTo(null);
        this.dispose();
    }//GEN-LAST:event_btnItemWiseReportActionPerformed

    private void btnLowStockReportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLowStockReportActionPerformed
        LowStockReport lowStockReport = new LowStockReport();
        lowStockReport.setVisible(true);
        lowStockReport.setLocationRelativeTo(null);
        this.dispose();
    }//GEN-LAST:event_btnLowStockReportActionPerformed

    private void btnExpiryReportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExpiryReportActionPerformed
        ExpiryReport expiryReport = new ExpiryReport();
         expiryReport.setVisible(true);
         expiryReport.setLocationRelativeTo(null);
         this.dispose();
    }//GEN-LAST:event_btnExpiryReportActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new Reports().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnExpiryReport;
    private javax.swing.JButton btnItemWiseReport;
    private javax.swing.JButton btnLowStockReport;
    private javax.swing.JButton btnSalesReport;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
